[versions]
jvmTarget = "11"

[libraries]
dependencyCheck = "org.owasp:dependency-check-gradle:7.4.4"
sonarQube = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin:4.4.1.3373"
licenseReport = "com.github.jk1:gradle-license-report:2.5"
kotlinxDatetime = "org.jetbrains.kotlinx:kotlinx-datetime:0.4.1"
kotlinxSerialization-core = "org.jetbrains.kotlinx:kotlinx-serialization-core:1.6.0"
kotlinxSerialization-json = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.6.0"

databaseDrivers-postgres = "org.postgresql:postgresql:42.4.0"
databaseDrivers-mssql = "com.microsoft.sqlserver:mssql-jdbc:10.2.1.jre8"

test-junit-engine = "org.junit.jupiter:junit-jupiter-engine:5.10.0"
test-junit-params = "org.junit.jupiter:junit-jupiter-params:5.10.0"

[plugins]
pluginPublish = "com.gradle.plugin-publish:1.2.1"
spotless = "com.diffplug.spotless:6.22.0"
